// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserFindAllRequest
	UserFindOneRequest
	UserSaveRequest
	UserResponse
	UsersResponse
	UserSaveResponse
	User
	UserSearch
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// REQUESTS
type UserFindAllRequest struct {
	UserSearch *UserSearch `protobuf:"bytes,1,opt,name=userSearch" json:"userSearch,omitempty"`
	Limit      int32       `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	StartKey   string      `protobuf:"bytes,3,opt,name=startKey" json:"startKey,omitempty"`
}

func (m *UserFindAllRequest) Reset()                    { *m = UserFindAllRequest{} }
func (m *UserFindAllRequest) String() string            { return proto.CompactTextString(m) }
func (*UserFindAllRequest) ProtoMessage()               {}
func (*UserFindAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserFindAllRequest) GetUserSearch() *UserSearch {
	if m != nil {
		return m.UserSearch
	}
	return nil
}

type UserFindOneRequest struct {
	UserSearch *UserSearch `protobuf:"bytes,1,opt,name=userSearch" json:"userSearch,omitempty"`
}

func (m *UserFindOneRequest) Reset()                    { *m = UserFindOneRequest{} }
func (m *UserFindOneRequest) String() string            { return proto.CompactTextString(m) }
func (*UserFindOneRequest) ProtoMessage()               {}
func (*UserFindOneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserFindOneRequest) GetUserSearch() *UserSearch {
	if m != nil {
		return m.UserSearch
	}
	return nil
}

type UserSaveRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserSaveRequest) Reset()                    { *m = UserSaveRequest{} }
func (m *UserSaveRequest) String() string            { return proto.CompactTextString(m) }
func (*UserSaveRequest) ProtoMessage()               {}
func (*UserSaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserSaveRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UsersResponse struct {
	Users   []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	LastKey string  `protobuf:"bytes,2,opt,name=lastKey" json:"lastKey,omitempty"`
}

func (m *UsersResponse) Reset()                    { *m = UsersResponse{} }
func (m *UsersResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()               {}
func (*UsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserSaveResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserSaveResponse) Reset()                    { *m = UserSaveResponse{} }
func (m *UserSaveResponse) String() string            { return proto.CompactTextString(m) }
func (*UserSaveResponse) ProtoMessage()               {}
func (*UserSaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserSaveResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Address   string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Street    string `protobuf:"bytes,6,opt,name=street" json:"street,omitempty"`
	PostCode  string `protobuf:"bytes,7,opt,name=postCode" json:"postCode,omitempty"`
	City      string `protobuf:"bytes,8,opt,name=city" json:"city,omitempty"`
	Country   string `protobuf:"bytes,9,opt,name=country" json:"country,omitempty"`
	Phone     string `protobuf:"bytes,10,opt,name=phone" json:"phone,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type UserSearch struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	PostCode  string `protobuf:"bytes,5,opt,name=postCode" json:"postCode,omitempty"`
}

func (m *UserSearch) Reset()                    { *m = UserSearch{} }
func (m *UserSearch) String() string            { return proto.CompactTextString(m) }
func (*UserSearch) ProtoMessage()               {}
func (*UserSearch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*UserFindAllRequest)(nil), "pb.UserFindAllRequest")
	proto.RegisterType((*UserFindOneRequest)(nil), "pb.UserFindOneRequest")
	proto.RegisterType((*UserSaveRequest)(nil), "pb.UserSaveRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
	proto.RegisterType((*UsersResponse)(nil), "pb.UsersResponse")
	proto.RegisterType((*UserSaveResponse)(nil), "pb.UserSaveResponse")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*UserSearch)(nil), "pb.UserSearch")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for UserService service

type UserServiceClient interface {
	FindOne(ctx context.Context, in *UserFindOneRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// rpc FindAll (UsersRequest) returns (UsersResponse) {}
	Save(ctx context.Context, in *UserSaveRequest, opts ...grpc.CallOption) (*UserSaveResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) FindOne(ctx context.Context, in *UserFindOneRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/FindOne", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Save(ctx context.Context, in *UserSaveRequest, opts ...grpc.CallOption) (*UserSaveResponse, error) {
	out := new(UserSaveResponse)
	err := grpc.Invoke(ctx, "/pb.UserService/Save", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	FindOne(context.Context, *UserFindOneRequest) (*UserResponse, error)
	// rpc FindAll (UsersRequest) returns (UsersResponse) {}
	Save(context.Context, *UserSaveRequest) (*UserSaveResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UserFindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(UserServiceServer).FindOne(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _UserService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UserSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(UserServiceServer).Save(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOne",
			Handler:    _UserService_FindOne_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _UserService_Save_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x53, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0xad, 0x64, 0xc9, 0xb6, 0xae, 0x5b, 0xd7, 0x4c, 0x8d, 0x19, 0x4c, 0x29, 0x45, 0xab, 0x2e,
	0x8a, 0x5a, 0x6c, 0xfa, 0x01, 0xa5, 0xa5, 0x50, 0x02, 0x09, 0x28, 0xf8, 0x03, 0x64, 0xe9, 0x06,
	0x0f, 0xc8, 0x92, 0x32, 0x33, 0x36, 0xe8, 0x0f, 0xf2, 0xc9, 0x59, 0x46, 0xf3, 0x90, 0x64, 0xad,
	0x12, 0x02, 0xd9, 0xcd, 0x39, 0xf7, 0x5c, 0x9d, 0xfb, 0x12, 0xc0, 0x49, 0x20, 0x8f, 0x2a, 0x5e,
	0xca, 0x92, 0xb8, 0xd5, 0x3e, 0x3c, 0x03, 0xd9, 0x35, 0xcc, 0x3f, 0x56, 0x64, 0xbf, 0xf3, 0x3c,
	0xc6, 0xfb, 0x13, 0x0a, 0x49, 0x22, 0xa3, 0xbb, 0xc5, 0x84, 0xa7, 0x07, 0xea, 0x7c, 0x75, 0xbe,
	0xcd, 0x36, 0xf3, 0xa8, 0xda, 0x47, 0xbb, 0x8e, 0x8d, 0x2f, 0x14, 0x64, 0x09, 0x7e, 0xce, 0x8e,
	0x4c, 0x52, 0xb7, 0x91, 0xfa, 0xb1, 0x01, 0x64, 0x0d, 0x53, 0x21, 0x13, 0x2e, 0xaf, 0xb0, 0xa6,
	0xa3, 0x26, 0x10, 0xc4, 0x1d, 0x0e, 0xff, 0xf6, 0xbe, 0x37, 0x05, 0xbe, 0xd2, 0x37, 0xfc, 0x01,
	0x1f, 0x75, 0x24, 0x39, 0x77, 0x9f, 0xf8, 0x0c, 0x9e, 0x12, 0xd8, 0xe4, 0x69, 0x9b, 0x1c, 0x6b,
	0x36, 0xfc, 0x0e, 0xef, 0x35, 0x42, 0x51, 0x95, 0x85, 0xc0, 0x67, 0xd4, 0xff, 0xe1, 0x83, 0x42,
	0xa2, 0x93, 0x7f, 0x01, 0x5f, 0x05, 0x44, 0xa3, 0x1f, 0x0d, 0xf4, 0x86, 0x26, 0x14, 0x26, 0x79,
	0x22, 0x74, 0xc3, 0xae, 0x6e, 0xb8, 0x85, 0xe1, 0x4f, 0x58, 0xf4, 0x95, 0xbe, 0xc8, 0xfc, 0xd1,
	0x01, 0x4f, 0x41, 0x32, 0x07, 0x97, 0x65, 0x5a, 0x14, 0xc4, 0xcd, 0xab, 0x49, 0x0b, 0xee, 0x18,
	0x17, 0xf2, 0x3a, 0x39, 0xa2, 0xb5, 0xe9, 0x09, 0x35, 0x74, 0xe5, 0xa9, 0x83, 0x76, 0xe8, 0x2d,
	0x56, 0x6b, 0xc2, 0x63, 0xc2, 0x72, 0xea, 0xe9, 0x80, 0x01, 0xaa, 0xe8, 0x24, 0xcb, 0x38, 0x0a,
	0x41, 0x7d, 0x53, 0xb4, 0x85, 0x64, 0x05, 0x63, 0x21, 0x39, 0xa2, 0xa4, 0x63, 0x1d, 0xb0, 0x48,
	0x79, 0x54, 0xa5, 0x90, 0x7f, 0xca, 0x0c, 0xe9, 0xc4, 0x78, 0xb4, 0x98, 0x10, 0xf0, 0x52, 0x26,
	0x6b, 0x3a, 0xd5, 0xbc, 0x7e, 0x2b, 0x87, 0xb4, 0x3c, 0x15, 0x92, 0xd7, 0x34, 0x30, 0x0e, 0x16,
	0xaa, 0x8a, 0xaa, 0x43, 0x59, 0x20, 0x05, 0x53, 0x91, 0x06, 0xe1, 0x83, 0x03, 0xd0, 0x6f, 0xfc,
	0xcd, 0x07, 0x70, 0xd9, 0x8e, 0x3f, 0x6c, 0x67, 0x53, 0xc3, 0xcc, 0x54, 0xc2, 0xcf, 0x2c, 0x45,
	0xf2, 0x0b, 0x26, 0xf6, 0x64, 0xc9, 0xaa, 0xdd, 0xd7, 0xf0, 0x86, 0xd7, 0x8b, 0x6e, 0x8f, 0x76,
	0xcf, 0xe1, 0x3b, 0xb2, 0x05, 0x4f, 0x6d, 0x9e, 0x7c, 0xea, 0x6e, 0xb9, 0xbf, 0xd8, 0xf5, 0x72,
	0x48, 0xb6, 0x49, 0xfb, 0xb1, 0xfe, 0x4b, 0xb7, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x18, 0x71,
	0xc5, 0x3f, 0xb3, 0x03, 0x00, 0x00,
}
